/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/models/stairs.glb --transform 
Files: src/assets/models/stairs.glb [8.52KB] > /Users/federicomartin/Desktop/Programación/Portfolio/character-controller/stairs-transformed.glb [1.88KB] (78%)
Author: pampi2703 (https://sketchfab.com/pampi2703)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/stairs-6f449130719e47108c7a1bf6ae9f1db3
Title: stairs
*/

import { RigidBody } from "@react-three/rapier";
import modelURL from "../../assets/models/stairs.glb";
import { useGLTF } from "@react-three/drei";

export function Stairs(props) {
	const { nodes } = useGLTF(modelURL);
	return (
		<group {...props} dispose={null} scale={0.075}>
			<RigidBody type="fixed" colliders="trimesh">
				<mesh
					geometry={nodes.Material2.geometry}
					position={[-30.236, 0, 0]}
					rotation={[-Math.PI / 2, 0, 0]}
				>
					<meshStandardMaterial metalness={0.7} roughness={0.3} />
				</mesh>
			</RigidBody>
		</group>
	);
}

useGLTF.preload(modelURL);
